version: "2"
formatters:
  enable:
    - gci
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    gofumpt:
      extra-rules: true
    golines:
      max-len: 80
      shorten-comments: true
      reformat-tags: true
