version: "2"
linters:
  enable:
    - protogetter
  settings:
    protogetter:
      skip-any-generated: true
      replace-first-arg-in-append: true
formatters:
  enable:
    - gci
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    gofumpt:
      extra-rules: true
    golines:
      max-len: 80
      shorten-comments: true
      reformat-tags: true
